Some changes

diff --git a/functions/zsh_functions b/functions/zsh_functions
--- a/functions/zsh_functions
+++ b/functions/zsh_functions
@@ -64,6 +64,11 @@ tmux new-session \; split-window -h \; select-pane -t 1 \; split-window -v \; at
 
 #__________________________________________________GIT
 function conf2git() {
+
+ local current_dir
+  current_dir=$(pwd)
+
+
   # Переходим в директорию ~/.aux
   if [ -d "$HOME/.aux" ]; then
     cd "$HOME/.aux" || { echo "Failed to enter ~/.aux directory"; return 1; }
@@ -86,11 +91,18 @@ function conf2git() {
 
   # Выполняем git push
   git push
+
+   # Возвращаемся в изначальную директорию
+  cd "$current_dir" || { echo "Failed to return to the original directory"; return 1; }
 }
 
 
 
 function git2conf() {
+ # Запоминаем текущую директорию
+  local current_dir
+  current_dir=$(pwd)
+
   # Переходим в директорию ~/.aux
   if [ -d "$HOME/.aux" ]; then
     cd "$HOME/.aux" || { echo "Failed to enter ~/.aux directory"; return 1; }
@@ -104,5 +116,7 @@ function git2conf() {
   git pull origin main || { echo "Failed to pull changes!"; return 1; }
 
   echo "Successfully pulled changes."
+   # Возвращаемся в изначальную директорию
+  cd "$current_dir" || { echo "Failed to return to the original directory"; return 1; }
 }
 
